---
title: "AE3UC1_12"
author: "* Jose Nunez, * Mario Alejandro Salcedo, Victor Manuel"
date: "15/10/2021"
output: 
  html_document:
    theme: cerulean
    toc: true
    toc_depth: 5
    toc_float: 
      collapsed: true
      smoth_scroll: true
    code_folding: "hide"
    code_download: TRUE
    highlight: "zenburn"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Introduccion

Coronavirus es una familia de 


```{r}
library(pacman) #para importar la biblioteca "pacman"
p_load("base64enc", "htmltools", "mime", "xfun", "prettydoc","readr", "knitr","DT","dplyr", "ggplot2","plotly", "gganimate","gifski","scales","ggdark")
```




# Importacion de datos
```{r }

#se realiza la declaración de las variables que contendrán las url en donde se encuentran los datos crudos de confirmados, decesos, recuperados

url_conf <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_confirmed_global.csv"

url_decesos <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_deaths_global.csv"

url_recuperados <- "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_time_series/time_series_covid19_recovered_global.csv"

#Leer los archivos .csv de las url 

datos_conf <- read.csv(url_conf)
datos_decesos <- read.csv(url_decesos)
datos_recuperados <- read.csv(url_recuperados)

#definir variables 

conf_mex <- t(datos_conf[datos_conf$Country.Region=="Mexico" ,])
dec_mex  <- t(datos_decesos[datos_decesos$Country.Region=="Mexico" ,])
rec_mex  <- t(datos_recuperados[datos_recuperados$Country.Region=="Mexico" ,])


#casos <- read.csv("docs/Casos_Diarios_Estado_Nacional_Confirmados_20211014.csv")

Fecha <- seq(from = as.Date("2020-01-22"), to = as.Date("2021-10-14"), by = "day"   )




```



```{r}



#casos confirmados 
vec1 <- as.vector(conf_mex)
vec2 <- vec1[5:636]
num1 <- as.numeric(vec2)
Confirmados <- as.vector(num1)

#decesos 
vec1 <- as.vector(dec_mex)
vec2 <- vec1[5:636]
num1 <- as.numeric(vec2)
Decesos <- as.vector(num1)

#recuperados
vec1 <- as.vector(rec_mex)
vec2 <- vec1[5:636]
num1 <- as.numeric(vec2)
Recuperados <- as.vector(num1)

#generación de un marco de datos (data frame)

datos1 <- data.frame(Fecha, Confirmados, Decesos, Recuperados)

```


```{r}
gcov <- ggplot(data = datos1) +
  geom_line(aes(Fecha, Confirmados, colour="Confirmados")) +
  geom_line(aes(Fecha, Decesos, colour="Decesos")) +
  geom_line(aes(Fecha, Recuperados, colour="Recuperados")) +
  xlab("Fecha") +
  ylab("COVID-19 en México") +
  labs(colour="casos")+
  ggtitle("Casos de COVID-19 en México (Fuente: JHU CSSE") +
  scale_y_continuous(labels = comma)
gcov
```


```{r}


ggplotly(gcov)
```











